#!/bin/sh

# Create environment configuration for runtime injection
cat > /usr/share/nginx/html/env-config.js << EOF
window._env_ = {
  VITE_API_URL: "${VITE_API_URL:-http://localhost:5000/api}",
  VITE_FIREBASE_API_KEY: "${VITE_FIREBASE_API_KEY}",
  VITE_FIREBASE_AUTH_DOMAIN: "${VITE_FIREBASE_AUTH_DOMAIN}",
  VITE_FIREBASE_PROJECT_ID: "${VITE_FIREBASE_PROJECT_ID}",
  VITE_FIREBASE_STORAGE_BUCKET: "${VITE_FIREBASE_STORAGE_BUCKET}",
  VITE_FIREBASE_MESSAGING_SENDER_ID: "${VITE_FIREBASE_MESSAGING_SENDER_ID}",
  VITE_FIREBASE_APP_ID: "${VITE_FIREBASE_APP_ID}",
  VITE_FIREBASE_MEASUREMENT_ID: "${VITE_FIREBASE_MEASUREMENT_ID}",
  VITE_FIREBASE_VAPID_KEY: "${VITE_FIREBASE_VAPID_KEY}",
  VITE_GOOGLE_MAPS_API_KEY: "${VITE_GOOGLE_MAPS_API_KEY}",
  VITE_STRIPE_PUBLISHABLE_KEY: "${VITE_STRIPE_PUBLISHABLE_KEY}",
  VITE_APP_ENVIRONMENT: "${VITE_APP_ENVIRONMENT:-production}"
};
EOF

# Start nginx
nginx -g "daemon off;"